In [6]:
import numpy as np

Diferencias entre np.matrix y np.ndarray
•	Jupyter notebook con makdwon
•	Comentarios o conclusiones
•	Codigo de python ejemplificando

### numpy.matrix 
Devuelve una matriz de un objeto similar a una matriz o de una cadena de datos. Una matriz es una matriz 2-D especializada que conserva su naturaleza 2-D a través de las operaciones. Tiene ciertos operadores especiales, como * (multiplicación de matrices) y ** (potencia de matriz).
data : array_like or string
If data is a string, it is interpreted as a matrix with commas or spaces separating columns, and semicolons separating rows.
dtype : data-type
Data-type of the output matrix.

##### Conclusión:
Este operador hace que la matriz creada mantenga dicho formato y forma bajo las operaciones que se le apliquen.

##### Ejemplo:

In [9]:
a = np.matrix('1 2; 3 4')
print (a)

[[1 2]
 [3 4]]


### numpy.ndarray 
Un objeto de matriz representa una matriz homogénea y multidimensional de elementos de tamaño fijo. Un objeto de tipo de datos asociado describe el formato de cada elemento de la matriz. 
Las matrices se deben construir utilizando matrices, ceros o vacíos. 

Forma: tupla de enteros
dtype: tipo de datos, opcional
Cualquier objeto que pueda ser interpretado como un tipo de datos numpy.

##### Conclusión:
Esto es un arreglo de número en forma de matriz, el cual se puede manipular o modificar. 

##### Ejemplo:

In [11]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[8.93527744e-312, 3.95252517e-323],
       [9.88131292e-324, 1.97626258e-323]])

In [15]:
np.ndarray((2,), buffer=np.array([1,2,3]),offset=np.int_().itemsize,dtype=int) 

array([2, 3])