In [18]:
import numpy as np

In [19]:
import tensorflow as tf

## El Dataset

In [20]:
## Importar datos desde el dataset.
dataset = "proyecto_training_data.npy"
data = np.load(dataset)
print(data) 
print(type(data))
print(data.shape)

[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]
<class 'numpy.ndarray'>
(1460, 6)


## 80% de los datos

In [21]:
## Slicing al dataset
trainingdata = data [:1168,]

print(trainingdata)
print("(Filas , Columnas) =", trainingdata.shape) 
print(type(trainingdata))

[[2.0850e+05 7.0000e+00 8.5600e+02 8.0000e+00 2.0030e+03 6.5000e+01]
 [1.8150e+05 6.0000e+00 1.2620e+03 6.0000e+00 1.9760e+03 8.0000e+01]
 [2.2350e+05 7.0000e+00 9.2000e+02 6.0000e+00 2.0010e+03 6.8000e+01]
 ...
 [2.3317e+05 7.0000e+00 1.5020e+03 7.0000e+00 2.0090e+03 7.9000e+01]
 [2.4535e+05 8.0000e+00 1.6940e+03 7.0000e+00 2.0080e+03 6.4000e+01]
 [1.7300e+05 6.0000e+00 9.5900e+02 7.0000e+00 2.0000e+03 5.8000e+01]]
(Filas , Columnas) = (1168, 6)
<class 'numpy.ndarray'>


## 20% de los datos

In [22]:
## Slicing al dataset 
dataprueba = data [1168:,]

print(dataprueba)
print("(Filas , Columnas) =", dataprueba.shape)
print(type(dataprueba))

[[2.35000e+05 6.00000e+00 1.23600e+03 7.00000e+00 1.93500e+03 1.20000e+02]
 [6.25000e+05 1.00000e+01 1.83100e+03 1.00000e+01 1.99500e+03 1.18000e+02]
 [1.71000e+05 6.00000e+00 1.11800e+03 6.00000e+00 1.97700e+03 7.60000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]
(Filas , Columnas) = (292, 6)
<class 'numpy.ndarray'>


# Extracción de los datos por Columnas

In [23]:
# Extracción por columnas del 80%

saleprice=trainingdata[:,0]
quality=trainingdata[:,1]

print(saleprice,"de tipo ", type(saleprice),"de rango ",saleprice.ndim, "de la forma ",saleprice.shape)
print(quality,"de tipo ", type(quality),"de rango ",quality.ndim, "de la forma ",quality.shape)

[208500. 181500. 223500. ... 233170. 245350. 173000.] de tipo  <class 'numpy.ndarray'> de rango  1 de la forma  (1168,)
[7. 6. 7. ... 7. 8. 6.] de tipo  <class 'numpy.ndarray'> de rango  1 de la forma  (1168,)


In [24]:
# Extracción por Columnas del 20%

saleprice20=dataprueba[:,0]
quality20=dataprueba[:,1]

## Las dos variables con mayor poder predictivo (Mayor correlación)
1. La variable Quality tiene un coeficiente de correlación de 0.79
2. La variable Square Feet tiene un coeficiente de correlación de 0.61

Dado que cada extracción de columna era un vector de 1168 filas, ahora lo convertiremos en una matriz de (1168,1)

In [25]:
saleprice=np.reshape(saleprice,(1168,1)) 
quality=np.reshape(quality,(1168,1)) 

print(saleprice,"de tipo ", type(saleprice),"de rango ",saleprice.ndim, "de la forma ",saleprice.shape)
print(quality,"de tipo ", type(quality),"de rango ",quality.ndim, "de la forma ",quality.shape)

[[208500.]
 [181500.]
 [223500.]
 ...
 [233170.]
 [245350.]
 [173000.]] de tipo  <class 'numpy.ndarray'> de rango  2 de la forma  (1168, 1)
[[7.]
 [6.]
 [7.]
 ...
 [7.]
 [8.]
 [6.]] de tipo  <class 'numpy.ndarray'> de rango  2 de la forma  (1168, 1)


Dado que cada extracción de columna era un vector de 292 filas, ahora lo convertiremos en una matriz de (292,1)

In [26]:
# Extracción por Columnas del 20%

saleprice20=np.reshape(saleprice20,(292,1)) 
quality20=np.reshape(quality20,(292,1)) 

print(saleprice20,"de tipo ", type(saleprice20),"de rango ",saleprice20.ndim, "de la forma ",saleprice20.shape)
print(quality20,"de tipo ", type(quality20),"de rango ",quality20.ndim, "de la forma ",quality20.shape)

[[235000.]
 [625000.]
 [171000.]
 [163000.]
 [171900.]
 [200500.]
 [239000.]
 [285000.]
 [119500.]
 [115000.]
 [154900.]
 [ 93000.]
 [250000.]
 [392500.]
 [745000.]
 [120000.]
 [186700.]
 [104900.]
 [ 95000.]
 [262000.]
 [195000.]
 [189000.]
 [168000.]
 [174000.]
 [125000.]
 [165000.]
 [158000.]
 [176000.]
 [219210.]
 [144000.]
 [178000.]
 [148000.]
 [116050.]
 [197900.]
 [117000.]
 [213000.]
 [153500.]
 [271900.]
 [107000.]
 [200000.]
 [140000.]
 [290000.]
 [189000.]
 [164000.]
 [113000.]
 [145000.]
 [134500.]
 [125000.]
 [112000.]
 [229456.]
 [ 80500.]
 [ 91500.]
 [115000.]
 [134000.]
 [143000.]
 [137900.]
 [184000.]
 [145000.]
 [214000.]
 [147000.]
 [367294.]
 [127000.]
 [190000.]
 [132500.]
 [101800.]
 [142000.]
 [130000.]
 [138887.]
 [175500.]
 [195000.]
 [142500.]
 [265900.]
 [224900.]
 [248328.]
 [170000.]
 [465000.]
 [230000.]
 [178000.]
 [186500.]
 [169900.]
 [129500.]
 [119000.]
 [244000.]
 [171750.]
 [130000.]
 [294000.]
 [165400.]
 [127500.]
 [301500.]
 [ 99900.]
 [190000.]

# Creación del Gráfo

In [84]:
grafoInicial = tf.Graph()
with grafoInicial.as_default():
    # cargando datos como constantes 
    trainingY = tf.constant(saleprice)
    trainingX = tf.constant(quality)
    pruebaY = tf.constant(saleprice20)
    pruebaX = tf.constant(quality20)
    
    #placeholder:
    ph_learningrate = tf.placeholder(dtype = tf.float64)    
  
    #Parametros beta1 y beta2:
    #Variables
    #Estimadores = tf.Variable(np.array([[0],[0]]))
    est0 = tf.Variable(0.0, name = "b0", dtype = tf.float64)
    est1 = tf.Variable(0.0, name = "b1", dtype = tf.float64)     
    
    #Parte de Entrenamiento
    #yhat = tf.matmul(trainingX, estimadores)
    #Hipotesis
    yhat = tf.add(tf.multiply(trainingX, est1), est0)
    
    #Costo
    error = (tf.reduce_mean(tf.pow(trainingY-yhat,2)))*.5
    
    ##para tensorboard
    Summary1st = tf.summary.scalar(name='1st._Summary_Escalar', tensor=error)
    
    # gradient descent un nodo mas del grafo
    optimizador = tf.train.GradientDescentOptimizer(ph_learningrate).minimize(error) 

In [97]:
<img src="GRAFO.PNG">

SyntaxError: invalid syntax (<ipython-input-97-f0ea5e034912>, line 1)

## Primera Sesion

In [85]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs', session.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session.run([error, optimizador],feed_dict={ph_learningrate:10.0})
        summary = session.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session.run(est1), "Beta0:", session.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 11879476.738013685 Beta0: 1805902.7739726028
Iteracion: 2 Error: 4.5991659790119325e+20 Beta1: 1892177310679.6533 Beta0: 295456331982.5073
Iteracion: 4 Error: 1.1741538548192451e+31 Beta1: 3.02332463745082e+17 Beta0: 4.720808510516164e+16
Iteracion: 6 Error: 2.9975810420448657e+41 Beta1: 4.830674176285755e+22 Beta0: 7.542917317082002e+21
Iteracion: 8 Error: 7.652738239325503e+51 Beta1: 7.718460898434383e+27 Beta0: 1.2052088434742129e+27
Iteracion: 10 Error: 1.9537220758403224e+62 Beta1: 1.2332572321502991e+33 Beta0: 1.925685110055494e+32
Iteracion: 12 Error: 4.987796302781102e+72 Beta1: 1.970500881800828e+38 Beta0: 3.076863535451501e+37
Iteracion: 14 Error: 1.2733700594203426e+83 Beta1: 3.148470265532254e+43 Beta0: 4.9162187350133154e+42
Iteracion: 16 Error: 3.250877160568992e+93 Beta1: 5.030632112116291e+48 Beta0: 7.855144166135146e+47
Iteracion: 18 Error: 8.299395949296999e+103 Beta1: 8.037954089802256e+53 Beta0: 1.25509651210

## Segunda Sesion

In [86]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session2:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs2', session2.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session2.run([error, optimizador],feed_dict={ph_learningrate:2.0})
        summary = session2.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session2.run(est1), "Beta0:", session2.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 2375895.347602737 Beta0: 361180.55479452055
Iteracion: 2 Error: 7.068508421135425e+17 Beta1: 14687549353.670645 Beta0: 2293379256.672861
Iteracion: 4 Error: 2.7734631500773237e+25 Beta1: 92001657821379.4 Beta0: 14365715233441.164
Iteracion: 6 Error: 1.0882207957947e+33 Beta1: 5.762924945647579e+17 Beta0: 8.998592077051824e+16
Iteracion: 8 Error: 4.26984039923888e+40 Beta1: 3.6098592925977763e+21 Beta0: 5.6366604694711645e+20
Iteracion: 10 Error: 1.6753527506022846e+48 Beta1: 2.261192751121447e+25 Beta0: 3.5307680330468105e+24
Iteracion: 12 Error: 6.573563825596209e+55 Beta1: 1.4163966634956459e+29 Beta0: 2.2116504924687565e+28
Iteracion: 14 Error: 2.579262269014906e+63 Beta1: 8.872218024609433e+32 Beta0: 1.3853637098374771e+32
Iteracion: 16 Error: 1.0120224019823023e+71 Beta1: 5.557500572045525e+36 Beta0: 8.677829589576449e+35
Iteracion: 18 Error: 3.970861569285819e+78 Beta1: 3.4811827800688027e+40 Beta0: 5.4357369007856226e+39


## Tercera Sesion

In [87]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session3:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs3', session3.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session3.run([error, optimizador],feed_dict={ph_learningrate:0.4})
        summary = session3.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session3.run(est1), "Beta0:", session3.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 475179.06952054746 Beta0: 72236.11095890412
Iteracion: 2 Error: 919083289664173.4 Beta1: 100600442.13487808 Beta0: 15702610.085544482
Iteracion: 4 Error: 4.6889465404191195e+19 Beta1: 22715865980.67634 Beta0: 3546988194.733801
Iteracion: 6 Error: 2.3921937036475336e+24 Beta1: 5130849043962.852 Beta0: 801162903271.941
Iteracion: 8 Error: 1.2204427298557604e+29 Beta1: 1158910147336838.0 Beta0: 180959491356535.38
Iteracion: 10 Error: 6.226420772643428e+33 Beta1: 2.6176422777026896e+17 Beta0: 4.087350656628539e+16
Iteracion: 12 Error: 3.1765780310385773e+38 Beta1: 5.912495554509265e+19 Beta0: 9.23214099684292e+18
Iteracion: 14 Error: 1.620617744244241e+43 Beta1: 1.335461456283324e+22 Beta0: 2.0852731890603742e+21
Iteracion: 16 Error: 8.268022530208811e+47 Beta1: 3.0164205364318357e+24 Beta0: 4.710028014629614e+23
Iteracion: 18 Error: 4.2181567370113103e+52 Beta1: 6.813220111893182e+26 Beta0: 1.0638588754210767e+26


## Cuarta Sesion

In [88]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session4:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs4', session4.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session4.run([error, optimizador],feed_dict={ph_learningrate:0.08})
        summary = session4.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session4.run(est1), "Beta0:", session4.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 95035.81390410948 Beta0: 14447.222191780822
Iteracion: 2 Error: 427871038356.74615 Beta1: 347767.9445346079 Beta0: 53130.32190068177
Iteracion: 4 Error: 10097732530878.422 Beta1: 1576990.5372376184 Beta0: 244294.6587574294
Iteracion: 6 Error: 239018887157757.66 Beta1: 7557388.730089376 Beta0: 1177343.1753135358
Iteracion: 8 Error: 5658421922992863.0 Beta1: 36654916.36768675 Beta0: 5720050.929573888
Iteracion: 10 Error: 1.3395555936240506e+17 Beta1: 178230208.48798063 Beta0: 27825747.307324126
Iteracion: 12 Error: 3.1712191391983324e+18 Beta1: 867072721.9202883 Beta0: 135385182.1586864
Iteracion: 14 Error: 7.50743826647455e+19 Beta1: 4218676283.4332314 Beta0: 658724815.84312
Iteracion: 16 Error: 1.7772858598969686e+21 Beta1: 20526101271.66503 Beta0: 3205067585.375658
Iteracion: 18 Error: 4.2074871823433864e+22 Beta1: 99870841954.2373 Beta0: 15594451783.31992


## Quinta Sesion

In [89]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session5:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs5', session5.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session5.run([error, optimizador],feed_dict={ph_learningrate:0.016})
        summary = session5.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session5.run(est1), "Beta0:", session5.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 19007.1627808219 Beta0: 2889.4444383561645
Iteracion: 2 Error: 1692717920.729602 Beta1: 28293.222901513873 Beta0: 4182.70020983109
Iteracion: 4 Error: 1398222565.9951367 Beta1: 29509.72899052926 Beta0: 4216.162627106623
Iteracion: 6 Error: 1392606374.9093754 Beta1: 29687.119692413442 Beta0: 4087.608068732467
Iteracion: 8 Error: 1391782214.470255 Beta1: 29730.676277016206 Beta0: 3938.3924651157217
Iteracion: 10 Error: 1391039721.833484 Beta1: 29756.968208974962 Beta0: 3786.7173443925567
Iteracion: 12 Error: 1390300789.3111522 Beta1: 29781.005715504754 Beta0: 3634.926139607562
Iteracion: 14 Error: 1389564115.1480346 Beta1: 29804.721650454238 Beta0: 3483.320301335709
Iteracion: 16 Error: 1388829671.1032403 Beta1: 29828.364946988328 Beta0: 3331.9383427672706
Iteracion: 18 Error: 1388097450.0717597 Beta1: 29851.96770652698 Beta0: 3180.7849201657164


## Sexta Sesion

In [91]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session6:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs6', session6.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session6.run([error, optimizador],feed_dict={ph_learningrate:0.0032})
        summary = session6.run(Summary1st)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session6.run(est1), "Beta0:", session6.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 3801.4325561643795 Beta0: 577.8888876712329
Iteracion: 2 Error: 11799490087.577244 Beta1: 10005.289566424328 Beta0: 1515.2239042581946
Iteracion: 4 Error: 7403995525.092175 Beta1: 14721.239249571898 Beta0: 2220.237254894668
Iteracion: 6 Error: 4865232463.641308 Beta1: 18306.40972943273 Beta0: 2748.6931594839843
Iteracion: 8 Error: 3398859301.158277 Beta1: 21032.211008549144 Beta0: 3142.9712734198756
Iteracion: 10 Error: 2551864936.7468405 Beta1: 23104.909086641164 Beta0: 3435.2792593468553
Iteracion: 12 Error: 2062604371.5923862 Beta1: 24681.261865955646 Beta0: 3650.094275385715
Iteracion: 14 Error: 1779959663.3890643 Beta1: 25880.40211658262 Beta0: 3806.018455788852
Iteracion: 16 Error: 1616649829.9175577 Beta1: 26792.86828481314 Beta0: 3917.189037938364
Iteracion: 18 Error: 1522264114.2392185 Beta1: 27487.46772108156 Beta0: 3994.350029757419


In [94]:
feed_dict={l_rate1: 10, l_rate2: 2, l_rate3: 0.4, l_rate4: 0.08, l_rate5: 0.016, l_rate6: 0.0032}

NameError: name 'l_rate1' is not defined